apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dice-ingress
  namespace: dice-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: dice-tls
  rules:
  - host: {{.Values.domain}}
    http:
      paths: 
      - path: /
        # pathType: Prefix
        backend:
          serviceName: dice-svc
          servicePort: 3000
