apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dice-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: dice-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - k8s.{{.Values.domain}}
    secretName: dice-tls
  rules:
  - host: k8s.{{.Values.domain}}
    http:
      paths: 
      - path: /dice
        pathType: Prefix
        backend:
          serviceName: dice-svc
          servicePort: 3000
