// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/roll": {
            "post": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roll"
                ],
                "summary": "roll dice based on json post",
                "parameters": [
                    {
                        "description": "roll",
                        "name": "roll",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/newdice.RollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/newdice.RollResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "newdice.DieRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "highest": {
                    "type": "integer"
                },
                "lowest": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "newdice.DieResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "highest": {
                    "type": "integer"
                },
                "highest-kept": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "lowest": {
                    "type": "integer"
                },
                "lowest-kept": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rolls": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "size": {
                    "type": "integer"
                },
                "subtotal": {
                    "type": "integer"
                },
                "unkept": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "newdice.RollRequest": {
            "type": "object",
            "properties": {
                "dice": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/newdice.DieRequest"
                    }
                }
            }
        },
        "newdice.RollResponse": {
            "type": "object",
            "properties": {
                "dice": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/newdice.DieResponse"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
