definitions:
  dice.DieRequest:
    properties:
      count:
        type: integer
      highest:
        type: integer
      size:
        type: integer
    type: object
  dice.DieResponse:
    properties:
      count:
        type: integer
      highest:
        type: integer
      highest-kept:
        items:
          type: integer
        type: array
      rolls:
        items:
          type: integer
        type: array
      size:
        type: integer
      subtotal:
        type: integer
      unkept:
        description: LowestKept  []int `json:"lowest-kept"`
        items:
          type: integer
        type: array
    type: object
  dice.RollRequest:
    properties:
      dice:
        items:
          $ref: '#/definitions/dice.DieRequest'
        type: array
    type: object
  dice.RollResponse:
    properties:
      dice:
        items:
          $ref: '#/definitions/dice.DieResponse'
        type: array
      image:
        type: string
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /roll:
    post:
      consumes:
      - application/json
      parameters:
      - description: roll
        in: body
        name: roll
        required: true
        schema:
          $ref: '#/definitions/dice.RollRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dice.RollResponse'
      summary: roll dice based on json post
      tags:
      - roll
  /roll/{input}:
    get:
      parameters:
      - description: input
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dice.RollResponse'
      summary: roll dice based on string input
      tags:
      - roll
  /rollImage/{input}:
    get:
      parameters:
      - description: input
        in: path
        name: input
        required: true
        type: string
      responses: {}
      summary: roll dice based on string input and return image
      tags:
      - roll
swagger: "2.0"
