on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:

  build:
    name: Build and Push image to Docker
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master
    
    - name: Login to DockerHub
      uses: crazy-max/ghaction-docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest
    
    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest
