# See example action for DO K8s: https://github.com/do-community/example-doctl-action/blob/master/.github/workflows/workflow.yaml
# See example action for DockerHub: https://github.com/marketplace/actions/docker-login

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master
    
    - name: Login to DockerHub
      uses: crazy-max/ghaction-docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest
    
    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_K8S_CLUSTER }}

    - name: Deploy to DigitalOcean Kubernetes
      run: helm install -f $GITHUB_WORKSPACE/dice/values.yaml dice $GITHUB_WORKSPACE/dice

    - name: Verify deployment
      run: helm status dice
