on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master
    
    - name: Login to DockerHub
      uses: crazy-max/ghaction-docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest
    
    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godice:latest

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_K8S_CLUSTER }}

    - name: Deploy to DigitalOcean Kubernetes
      run: helm upgrade -f $GITHUB_WORKSPACE/dice/values.yaml dice $GITHUB_WORKSPACE/dice

    - name: Verify deployment
      run: helm status dice
